---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

allowed_cidrs:
  - '10.0.0.0/8'

database_name: 'testservicedb'
database_master_user: 'testservice'
database_master_user_password: 'testpassword'

database_family: "mysql5.7"

private_zone_id: 'Z0211739BXR21FNN139O'
